### ISSUE TITLE
minus (like -3) is minified with a space which leads to an error

### ISSUE THREAD

**Issue by blb4github** [klaashoekstra94/heishamon_rules_minify#5]
One of code lines is:
`#RoomTempControl = round(#RoomTempDelta * -3);`

When this line is minified it is changed to:
`#RTC = round(#RTD * - 3);`
with option -c:
`	#RoomTempControl = round(#RoomTempDelta * - 3);`

This is leading to an error, if I change the output lines manually to:
`#RTC = round(#RTD * -3);`
or
`	#RoomTempControl = round(#RoomTempDelta * -3);`
it is accepted.

update:
I have now done a work around:
`	$multiplier = -3;
	#RoomTempControl = round(#RoomTempDelta * $multiplier);`

**Comment by klaashoekstra94** [comment]
Good to see that this project is still being used :)
And good catch of that bug, It should hopefully be fixed by PR #6. I already made a new release ([v0.0.4](https://github.com/klaashoekstra94/heishamon_rules_minify/releases/tag/v0.0.4)), so you should be able to just update it using pip to test it.

**Comment by blb4github** [comment]
Thanks for fixing it, I have installed the new version and it's working perfect now!
